### ISSUE TITLE
Cannot enter final boss fight.

### ISSUE THREAD

**Issue by JokeDeity** [miguelcjalmeida/vagante-dsmod#3]
My friend and I have been obsessed with this game, but we NEED to know, can it be finished?  Is there a final boss fight?  The game always crashes for us either before loading the last locked room, or before loading the final boss fight.  Non-descript crash error.  We have had this happen dozens of times now (we love this mod, so we keep trying).  Anything you can tell us helps.

**Comment by JokeDeity** [comment]
Still trying to contact you.  Still playing this mod semi daily.  Still can't get to the final boss.

**Comment by miguelcjalmeida** [comment]
Hey joke deity, thanks for contacting. It's been so long i thought no one would ever play this mod again. Thanks for showing me wrong.

I can try pushing an experimental version in the weekend that you could try out for us. Would you like that?

Glad to hear you enjoyed the mod! Thanks for that.

YES THERE IS A SURPRISE IN THE BOSS FIGHT, OR SHOULD I SAY BOSSES? ;)

**Comment by JokeDeity** [comment]
Holy shit, yes!  I have tried to connect with you in so many ways, yes yes
yes!  My friend and I would be so grateful.  I literally had gotten to the
point I was trying to figure out how to edit it myself (very confusing).

**Comment by JokeDeity** [comment]
My friend is equally excited and said "tell him it's better than regular Vagante".  We play it often like I said, and it's unavoidable for us that the the game crashes EITHER at the moment loading into the second to last intermission, the last dungeon stage, or the boss fight (never seen the boss fight, it's always crashed at this point for us no matter what).  We have Discord and can talk on there if it's easier and you need to ask us anything or send me a data file to test.  Discord:  tRAINED bY dOG#0303

**Comment by JokeDeity** [comment]
We're dying to hear from you my man.

**Comment by miguelcjalmeida** [comment]
You should be able to enter the final boss now
